name: Test_Contract

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_contract:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: setup and test
        run: |
          npm cache clean --force
          npm install
          npx hardhat test
